const defaultCompanies = [
    'Tata Consultancy Services',
    'Infosys',
    'Wipro',
    'HCL Technologies',
    'Reliance Industries',
    'HDFC Bank',
    'ICICI Bank',
    'Axis Bank',
    'Bharti Airtel',
    'Sun Pharma',
    'ITC Limited',
    'Larsen & Toubro',
    'Mahindra & Mahindra',
    'State Bank of India',
    'NTPC Limited',
    'ONGC',
    'Adani Group',
    'Flipkart',
    'Zomato',
    'Swiggy',
    'Razorpay',
    'Freshworks',
    'Zoho',
    'BYJU\'S',
    'PhonePe',
    'Paytm',
    'Ola',
    'MakeMyTrip',
    'Titan Company',
    'Godrej'
];

module.exports = defaultCompanies;
